(function(){
  const pages={radar:['◉','小语种考试雷达','雷达'],calendar:['▦','全年考试日历','日历'],library:['◇','考试库','考试'],reminder:['✦','今日对内营销提醒','提醒']};
  const App={data:null,page:'radar',today:new Date(),calendarState:{year:new Date().getFullYear(),language:'',exam:'',month:0,q:'',view:'annual'},libraryState:{q:''},
    languages(){if(!this.data)return[];const dict=this.data.dictionaries.filter(x=>x.type==='语种').sort((a,b)=>Number(a.sort||999)-Number(b.sort||999)).map(x=>x.value),actual=[...this.data.basics,...this.data.sessions].map(x=>x.language).filter(Boolean);return[...new Set([...dict,...actual])]},
    version(){if(!this.data)return'';return this.data.sessions.map(x=>x.dataVersion).filter(Boolean).sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true})).at(-1)||'未填写'},
    renderNav(){const visible=Object.entries(pages),html=visible.map(([k,v])=>`<button class="nav-btn ${this.page===k?'active':''}" data-page="${k}"><span class="nav-icon">${v[0]}</span>${v[1]}</button>`).join('');document.querySelector('#sideNav').innerHTML=html;document.querySelector('#mobileNav').innerHTML=visible.map(([k,v])=>`<button class="nav-btn ${this.page===k?'active':''}" data-page="${k}"><span class="nav-icon">${v[0]}</span>${v[2]}</button>`).join('')},
    render(){this.renderNav();document.querySelector('#pageTitle').textContent=pages[this.page][1];const status=document.querySelector('#dataStatus');if(!this.data){status.innerHTML='<span class="status-pill">等待考试数据</span>';document.querySelector('#app').innerHTML=UI.welcome();return}status.innerHTML=`<span class="status-pill">数据版本：${UI.esc(this.version())}</span><span class="status-pill">${this.data.meta.readOnly?'在线共享数据':'最近导入：'+DateUtils.formatDateTime(this.data.meta.importedAt)}</span>`;try{document.querySelector('#app').innerHTML=this.page==='radar'?UI.radar(this.data,this.today):this.page==='calendar'?UI.calendar(this.data,this.calendarState):this.page==='library'?UI.library(this.data,this.libraryState):UI.reminder(this.data,this.today)}catch(e){console.error(e);document.querySelector('#app').innerHTML=`<div class="error">页面加载遇到问题：${UI.esc(e.message)}。请联系数据维护人员更新考试数据。</div>`}},
    toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>t.classList.remove('show'),2000)},
    async copy(text,msg){try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}this.toast(msg)},
    findEvent(id){return RadarEngine.buildExamEvents(this.data.sessions,this.data.rules,this.today).find(e=>e.eventId===id)},
    showMoments(id){const e=this.findEvent(id);if(!e)return;UI.modal(`<h2>${UI.esc(e.examName)} · 朋友圈文案</h2>${UI.momentsCard(this.data,e)}`)},
    async share(){if(location.protocol==='file:')return this.toast('请发布为网址后再分享给其他人');const payload={title:'新通小语种考试雷达',text:'查看近期考试节点、全年考试日历与顾问行动建议',url:location.href};try{if(navigator.share)await navigator.share(payload);else await this.copy(location.href,'分享链接已复制')}catch(e){if(e.name!=='AbortError')this.toast('暂时无法分享，请复制浏览器地址')}},
    async init(){try{this.data=await RadarStorage.get();if(!this.data&&location.protocol!=='file:')this.data=await ExcelLoader.loadHostedDefault()}catch(e){console.warn(e)}if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});this.render()}
  };
  window.App=App;
  document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;
    if(el.id==='shareTrigger'){App.share();return}if(el.dataset.page){App.page=el.dataset.page;App.render();return}if(el.dataset.detail){const s=App.data.sessions.find(x=>x.recordId===el.dataset.detail);if(s)UI.detail(s);return}if(el.dataset.basic){const b=App.data.basics.find(x=>x.examId===el.dataset.basic);if(b)UI.modal(UI.examInfo(b));return}if(el.dataset.moments){App.showMoments(el.dataset.moments);return}if(el.dataset.close!=null||el.classList.contains('modal-wrap')){document.querySelector('#modalRoot').innerHTML='';return}if(el.dataset.copyText){App.copy(decodeURIComponent(el.dataset.copyText),'已复制，可直接发送到企业微信群');return}
    if(el.dataset.examCalendar){const basicName=el.dataset.examCalendar,examId=el.dataset.examId,language=el.dataset.lang,session=App.data.sessions.find(s=>s.language===language&&examId&&s.examId===examId)||App.data.sessions.find(s=>s.language===language&&DataNormalizer.standardName(s.examName)===DataNormalizer.standardName(basicName))||App.data.sessions.find(s=>s.language===language&&(DataNormalizer.standardName(s.examName).includes(DataNormalizer.standardName(basicName))||DataNormalizer.standardName(basicName).includes(DataNormalizer.standardName(s.examName))));App.calendarState.language=language;App.calendarState.exam=session?.examName||basicName;App.calendarState.month=0;App.calendarState.q='';App.calendarState.view='annual';App.page='calendar';App.render();return}if(el.dataset.view){if(el.dataset.view==='month'&&App.calendarState.month===0)App.calendarState.month=App.today.getMonth()+1;App.calendarState.view=el.dataset.view;App.render();return}
    if(el.dataset.copyTab!=null){const card=el.closest('.moments-card'),event=App.findEvent(card.dataset.event),copies=TemplateEngine.buildMoments(App.data,event),i=+el.dataset.copyTab;card.querySelectorAll('.tab').forEach((x,j)=>x.classList.toggle('active',i===j));card.querySelector('.moment-content').innerHTML=`<h3>${UI.esc(copies[i].renderedTitle)}</h3><div class="copy-box moment-copy">${UI.esc(copies[i].renderedBody)}</div><div class="btns"><button class="btn poster-btn" data-poster>生成朋友圈配图</button><button class="btn primary" data-share-copy="${i}">分享文案</button><button class="btn outline" data-copy-body="${i}">复制正文</button><button class="btn outline" data-copy-all="${i}">复制标题+正文</button></div>`;return}
    if(el.hasAttribute('data-poster')){const card=el.closest('.moments-card'),event=App.findEvent(card.dataset.event);if(!event)return;el.disabled=true;el.textContent='正在生成…';PosterEngine.create(event).then(canvas=>{UI.modal(`<div class="poster-modal"><p class="section-kicker">SHINYWAY INFO POSTER</p><h2>${UI.esc(event.examName)} · 新通快讯配图</h2><p class="muted">采用新通快讯红色模板，考试内容根据当前数据自动替换。</p><div class="poster-preview"></div><div class="btns"><button class="btn primary" data-copy-poster>复制图片</button><button class="btn outline" data-download-poster>下载高清图片</button><button class="btn outline" data-share-poster>分享图片</button></div><p class="poster-copy-note">复制后可直接粘贴到企业微信或聊天窗口</p></div>`);document.querySelector('.poster-preview').append(canvas);App.poster={canvas,event}}).catch(()=>App.toast('配图生成失败，请稍后重试')).finally(()=>{el.disabled=false;el.textContent='生成朋友圈配图'});return}
    if(el.hasAttribute('data-copy-poster')){if(App.poster)PosterEngine.copy(App.poster.canvas).then(()=>App.toast('图片已复制，可直接粘贴发送')).catch(()=>App.toast('当前浏览器不支持复制图片，请使用下载或分享'));return}
    if(el.hasAttribute('data-download-poster')){if(App.poster)PosterEngine.download(App.poster.canvas,App.poster.event).then(()=>App.toast('朋友圈配图已下载'));return}
    if(el.hasAttribute('data-share-poster')){if(App.poster)PosterEngine.share(App.poster.canvas,App.poster.event).catch(e=>{if(e.name!=='AbortError')App.toast('暂时无法分享图片')});return}
    if(el.dataset.shareCopy!=null){const card=el.closest('.moments-card'),event=App.findEvent(card.dataset.event),c=TemplateEngine.buildMoments(App.data,event)[+el.dataset.shareCopy],text=`${c.renderedTitle}\n\n${c.renderedBody}`;if(navigator.share)navigator.share({title:c.renderedTitle,text}).catch(err=>{if(err.name!=='AbortError')App.copy(text,'分享不可用，文案已复制')});else App.copy(text,'文案已复制，可粘贴分享');return}
    if(el.dataset.copyBody!=null||el.dataset.copyAll!=null){const card=el.closest('.moments-card'),event=App.findEvent(card.dataset.event),i=+(el.dataset.copyBody??el.dataset.copyAll),c=TemplateEngine.buildMoments(App.data,event)[i];App.copy(el.dataset.copyBody!=null?c.renderedBody:`${c.renderedTitle}\n\n${c.renderedBody}`,'朋友圈文案已复制');return}
  });
  document.addEventListener('change',e=>{if(e.target.dataset.action!=null){localStorage.setItem(`radar-action-${DateUtils.dateKey(App.today)}-${e.target.dataset.action}`,e.target.checked?'1':'0');return}if(e.target.dataset.filter){App.calendarState[e.target.dataset.filter]=e.target.dataset.filter==='year'||e.target.dataset.filter==='month'?+e.target.value:e.target.value;if(e.target.dataset.filter==='language')App.calendarState.exam='';App.render()}});
  let inputTimer;document.addEventListener('input',e=>{if(e.target.dataset.filter==='q'){clearTimeout(inputTimer);inputTimer=setTimeout(()=>{App.calendarState.q=e.target.value;App.render()},250)}if(e.target.hasAttribute('data-library-q')){clearTimeout(inputTimer);inputTimer=setTimeout(()=>{App.libraryState.q=e.target.value;App.render()},250)}});
  App.init();
})();
