(function(){
  const pages={radar:['◉','小语种考试雷达','雷达'],calendar:['▦','全年考试日历','日历'],library:['◇','考试库','考试'],data:['⚙','数据管理','数据']};
  const App={data:null,page:'radar',today:new Date(),calendarState:{year:new Date().getFullYear(),language:'',exam:'',month:0,q:'',view:'annual'},libraryState:{q:''},
    authKey:'exam-radar-admin-hash',sessionKey:'exam-radar-admin-unlocked',
    isAdmin(){return sessionStorage.getItem(this.sessionKey)==='1'},
    isOwnerEnvironment(){return location.protocol==='file:'||['localhost','127.0.0.1'].includes(location.hostname)},
    async hashPassword(value,saltHex){const salt=new Uint8Array(saltHex.match(/.{2}/g).map(x=>parseInt(x,16))),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(value),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:150000,hash:'SHA-256'},key,256);return Array.from(new Uint8Array(bits)).map(x=>x.toString(16).padStart(2,'0')).join('')},
    showAdminEntry(){const configured=!!localStorage.getItem(this.authKey);UI.modal(`<div class="auth-box"><div class="auth-icon">⌁</div><p class="section-kicker">PRIVATE ACCESS</p><h2>${configured?'管理员验证':'设置管理员密码'}</h2><p class="auth-note">${configured?'验证通过后才能进入数据管理。关闭浏览器会自动退出管理会话。':'这是首次使用，请为本机数据管理设置专属密码。密码只以加盐派生值保存在当前浏览器。'}</p><input class="input" id="adminPassword" type="password" autocomplete="current-password" placeholder="${configured?'输入管理员密码':'设置至少 8 位密码'}">${configured?'':`<input class="input" id="adminPasswordConfirm" type="password" autocomplete="new-password" placeholder="再次输入密码">`}<div id="adminError" class="error" style="display:none"></div><button class="btn primary" style="width:100%;margin-top:8px" data-admin-submit="${configured?'login':'setup'}">${configured?'进入数据管理':'保存并进入管理'}</button></div>`);setTimeout(()=>document.querySelector('#adminPassword')?.focus(),50)},
    async submitAdmin(mode){const password=document.querySelector('#adminPassword')?.value||'',confirmValue=document.querySelector('#adminPasswordConfirm')?.value||'',error=document.querySelector('#adminError');const fail=msg=>{error.textContent=msg;error.style.display='block'};if(password.length<8)return fail('为保证安全，密码至少需要 8 位。');if(mode==='setup'&&password!==confirmValue)return fail('两次输入的密码不一致。');let salt,expected;if(mode==='setup'){const bytes=crypto.getRandomValues(new Uint8Array(16));salt=Array.from(bytes).map(x=>x.toString(16).padStart(2,'0')).join('')}else{try{({salt,hash:expected}=JSON.parse(localStorage.getItem(this.authKey)))}catch{return fail('管理员凭据损坏，请清理站点数据后重新初始化。')}}const hash=await this.hashPassword(password,salt);if(mode==='login'&&hash!==expected)return fail('管理员密码不正确。');if(mode==='setup')localStorage.setItem(this.authKey,JSON.stringify({salt,hash,version:1}));sessionStorage.setItem(this.sessionKey,'1');document.querySelector('#modalRoot').innerHTML='';this.page='data';this.render();this.toast('已进入管理员数据控制台')},
    lockAdmin(){sessionStorage.removeItem(this.sessionKey);this.page='radar';this.render();this.toast('已退出数据管理')},
    languages(){if(!this.data)return[];const dict=this.data.dictionaries.filter(x=>x.type==='语种').sort((a,b)=>Number(a.sort||999)-Number(b.sort||999)).map(x=>x.value),actual=[...this.data.basics,...this.data.sessions].map(x=>x.language).filter(Boolean);return[...new Set([...dict,...actual])]},
    version(){if(!this.data)return'';return this.data.sessions.map(x=>x.dataVersion).filter(Boolean).sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true})).at(-1)||'未填写'},
    renderNav(){const visible=Object.entries(pages).filter(([k])=>k!=='data'),html=visible.map(([k,v])=>`<button class="nav-btn ${this.page===k?'active':''}" data-page="${k}"><span class="nav-icon">${v[0]}</span>${v[1]}</button>`).join('');document.querySelector('#sideNav').innerHTML=html;document.querySelector('#mobileNav').innerHTML=visible.map(([k,v])=>`<button class="nav-btn ${this.page===k?'active':''}" data-page="${k}"><span class="nav-icon">${v[0]}</span>${v[2]}</button>`).join('')},
    render(){if(this.page==='data'&&(!this.isAdmin()||!this.isOwnerEnvironment()))this.page='radar';this.renderNav();document.querySelector('#pageTitle').textContent=pages[this.page][1];const trigger=document.querySelector('#adminTrigger');trigger.hidden=!this.isOwnerEnvironment();trigger.textContent=this.isAdmin()?'●':'⌁';trigger.title=this.isAdmin()?'返回数据管理':'管理员入口';const status=document.querySelector('#dataStatus');if(!this.data){status.innerHTML='<span class="status-pill">等待导入数据</span>';document.querySelector('#app').innerHTML=UI.welcome(this.isAdmin()&&this.isOwnerEnvironment());return}status.innerHTML=`<span class="status-pill">数据版本：${UI.esc(this.version())}</span><span class="status-pill">${this.data.meta.readOnly?'共享只读版':'最近导入：'+DateUtils.formatDateTime(this.data.meta.importedAt)}</span>`;try{document.querySelector('#app').innerHTML=this.page==='radar'?UI.radar(this.data,this.today):this.page==='calendar'?UI.calendar(this.data,this.calendarState):this.page==='library'?UI.library(this.data,this.libraryState):UI.management(this.data,this.today)}catch(e){console.error(e);document.querySelector('#app').innerHTML=`<div class="error">页面加载遇到问题：${UI.esc(e.message)}。请联系管理员更新考试数据。</div>`}},
    toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>t.classList.remove('show'),2000)},
    async copy(text,msg){try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}this.toast(msg)},
    import(){document.querySelector('#fileInput').click()},
    findEvent(id){return RadarEngine.buildExamEvents(this.data.sessions,this.data.rules,this.today).find(e=>e.eventId===id)},
    showMoments(id){const e=this.findEvent(id);if(!e)return;UI.modal(`<h2>${UI.esc(e.examName)} · 朋友圈文案</h2>${UI.momentsCard(this.data,e)}`)},
    async share(){if(location.protocol==='file:')return this.toast('请发布为网址后再分享给其他人');const payload={title:'新通小语种考试雷达',text:'查看近期考试节点、全年考试日历与顾问行动建议',url:location.href};try{if(navigator.share)await navigator.share(payload);else await this.copy(location.href,'分享链接已复制')}catch(e){if(e.name!=='AbortError')this.toast('暂时无法分享，请复制浏览器地址')}},
    async init(){try{this.data=await RadarStorage.get();if(!this.data&&!this.isOwnerEnvironment())this.data=await ExcelLoader.loadHostedDefault()}catch(e){console.warn(e)}if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});this.render()}
  };
  window.App=App;
  document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;
    if(el.id==='shareTrigger'){App.share();return}if(el.id==='adminTrigger'||el.hasAttribute('data-admin-open')){if(!App.isOwnerEnvironment())return;App.isAdmin()?(App.page='data',App.render()):App.showAdminEntry();return}if(el.dataset.adminSubmit){App.submitAdmin(el.dataset.adminSubmit);return}if(el.hasAttribute('data-admin-lock')){App.lockAdmin();return}if(el.dataset.page){App.page=el.dataset.page;App.render();return}if(el.hasAttribute('data-import')){if(!App.isAdmin()||!App.isOwnerEnvironment())return;App.import();return}if(el.dataset.detail){const s=App.data.sessions.find(x=>x.recordId===el.dataset.detail);if(s)UI.detail(s);return}if(el.dataset.basic){const b=App.data.basics.find(x=>x.examId===el.dataset.basic);if(b)UI.modal(UI.examInfo(b));return}if(el.dataset.moments){App.showMoments(el.dataset.moments);return}if(el.dataset.close!=null||el.classList.contains('modal-wrap')){document.querySelector('#modalRoot').innerHTML='';return}if(el.dataset.copyText){App.copy(decodeURIComponent(el.dataset.copyText),'已复制，可直接发送到企业微信群');return}
    if(el.dataset.examCalendar){const basicName=el.dataset.examCalendar,examId=el.dataset.examId,language=el.dataset.lang,session=App.data.sessions.find(s=>s.language===language&&examId&&s.examId===examId)||App.data.sessions.find(s=>s.language===language&&DataNormalizer.standardName(s.examName)===DataNormalizer.standardName(basicName))||App.data.sessions.find(s=>s.language===language&&(DataNormalizer.standardName(s.examName).includes(DataNormalizer.standardName(basicName))||DataNormalizer.standardName(basicName).includes(DataNormalizer.standardName(s.examName))));App.calendarState.language=language;App.calendarState.exam=session?.examName||basicName;App.calendarState.month=0;App.calendarState.q='';App.calendarState.view='annual';App.page='calendar';App.render();return}if(el.dataset.view){if(el.dataset.view==='month'&&App.calendarState.month===0)App.calendarState.month=App.today.getMonth()+1;App.calendarState.view=el.dataset.view;App.render();return}
    if(el.dataset.copyTab!=null){const card=el.closest('.moments-card'),event=App.findEvent(card.dataset.event),copies=TemplateEngine.buildMoments(App.data,event),i=+el.dataset.copyTab;card.querySelectorAll('.tab').forEach((x,j)=>x.classList.toggle('active',i===j));card.querySelector('.moment-content').innerHTML=`<h3>${UI.esc(copies[i].renderedTitle)}</h3><div class="copy-box moment-copy">${UI.esc(copies[i].renderedBody)}</div><div class="btns"><button class="btn poster-btn" data-poster>生成朋友圈配图</button><button class="btn primary" data-share-copy="${i}">分享文案</button><button class="btn outline" data-copy-body="${i}">复制正文</button><button class="btn outline" data-copy-all="${i}">复制标题+正文</button></div>`;return}
    if(el.hasAttribute('data-poster')){const card=el.closest('.moments-card'),event=App.findEvent(card.dataset.event);if(!event)return;el.disabled=true;el.textContent='正在生成…';PosterEngine.create(event).then(canvas=>{UI.modal(`<div class="poster-modal"><p class="section-kicker">SHINYWAY INFO POSTER</p><h2>${UI.esc(event.examName)} · 新通快讯配图</h2><p class="muted">采用新通快讯红色模板，考试内容根据当前数据自动替换。</p><div class="poster-preview"></div><div class="btns"><button class="btn primary" data-copy-poster>复制图片</button><button class="btn outline" data-download-poster>下载高清图片</button><button class="btn outline" data-share-poster>分享图片</button></div><p class="poster-copy-note">复制后可直接粘贴到企业微信或聊天窗口</p></div>`);document.querySelector('.poster-preview').append(canvas);App.poster={canvas,event}}).catch(()=>App.toast('配图生成失败，请稍后重试')).finally(()=>{el.disabled=false;el.textContent='生成朋友圈配图'});return}
    if(el.hasAttribute('data-copy-poster')){if(App.poster)PosterEngine.copy(App.poster.canvas).then(()=>App.toast('图片已复制，可直接粘贴发送')).catch(()=>App.toast('当前浏览器不支持复制图片，请使用下载或分享'));return}
    if(el.hasAttribute('data-download-poster')){if(App.poster)PosterEngine.download(App.poster.canvas,App.poster.event).then(()=>App.toast('朋友圈配图已下载'));return}
    if(el.hasAttribute('data-share-poster')){if(App.poster)PosterEngine.share(App.poster.canvas,App.poster.event).catch(e=>{if(e.name!=='AbortError')App.toast('暂时无法分享图片')});return}
    if(el.dataset.shareCopy!=null){const card=el.closest('.moments-card'),event=App.findEvent(card.dataset.event),c=TemplateEngine.buildMoments(App.data,event)[+el.dataset.shareCopy],text=`${c.renderedTitle}\n\n${c.renderedBody}`;if(navigator.share)navigator.share({title:c.renderedTitle,text}).catch(err=>{if(err.name!=='AbortError')App.copy(text,'分享不可用，文案已复制')});else App.copy(text,'文案已复制，可粘贴分享');return}
    if(el.dataset.copyBody!=null||el.dataset.copyAll!=null){const card=el.closest('.moments-card'),event=App.findEvent(card.dataset.event),i=+(el.dataset.copyBody??el.dataset.copyAll),c=TemplateEngine.buildMoments(App.data,event)[i];App.copy(el.dataset.copyBody!=null?c.renderedBody:`${c.renderedTitle}\n\n${c.renderedBody}`,'朋友圈文案已复制');return}
    if(el.hasAttribute('data-clear')){if(confirm('确定清除本机缓存的考试数据吗？此操作不会删除原 Excel 文件。'))RadarStorage.clear().then(()=>{App.data=null;App.page='radar';App.render();App.toast('本地数据已清除')});return}
  });
  document.addEventListener('change',e=>{if(e.target.id==='fileInput'){const file=e.target.files[0];if(!file)return;ExcelLoader.load(file).then(async data=>{await RadarStorage.set(data);App.data=data;App.page='radar';App.render();App.toast('考试数据导入成功')}).catch(err=>{App.toast('导入失败');UI.modal(`<h2>无法导入 Excel</h2><div class="error">${UI.esc(err.message)}</div><p class="muted">请检查文件格式与必要 Sheet 名称后重试。</p>`)}).finally(()=>e.target.value='');return}if(e.target.dataset.action!=null){localStorage.setItem(`radar-action-${DateUtils.dateKey(App.today)}-${e.target.dataset.action}`,e.target.checked?'1':'0');return}if(e.target.dataset.filter){App.calendarState[e.target.dataset.filter]=e.target.dataset.filter==='year'||e.target.dataset.filter==='month'?+e.target.value:e.target.value;if(e.target.dataset.filter==='language')App.calendarState.exam='';App.render()}});
  let inputTimer;document.addEventListener('input',e=>{if(e.target.dataset.filter==='q'){clearTimeout(inputTimer);inputTimer=setTimeout(()=>{App.calendarState.q=e.target.value;App.render()},250)}if(e.target.hasAttribute('data-library-q')){clearTimeout(inputTimer);inputTimer=setTimeout(()=>{App.libraryState.q=e.target.value;App.render()},250)}});
  App.init();
})();
