(function(){
  const original=UI.studyPlan,state={mode:'reference',plan:null};
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function key(plan=state.plan){return`custom-timeline-${plan?.country||'DE'}-${plan?.scenario||'highschool'}-${plan?.route||'direct'}`}
  function saved(){try{return JSON.parse(localStorage.getItem(key())||'null')}catch{return null}}
  function toolbar(){return`<div class="custom-timeline-tools"><div class="custom-mode-switch"><button class="${state.mode==='reference'?'active':''}" data-custom-mode="reference">参考时间轴</button><button class="${state.mode==='custom'?'active':''}" data-custom-mode="custom">个性时间轴</button></div><span class="custom-timeline-note">个性版本仅保存在当前浏览器</span><button class="custom-edit-button" data-custom-edit ${state.mode==='custom'?'':'hidden'}><span>✎</span>编辑时间与学习内容</button></div>`}
  UI.studyPlan=plan=>{state.plan={...plan};const html=original(plan);return html.replace(/(<section class="matrix-page[^>]*>)/,`$1${toolbar()}`)};
  function articles(){return[...document.querySelectorAll('#app .matrix-lane.language>article')]}
  function times(){return[...document.querySelectorAll('#app .matrix-time>div> b')]}
  function apply(){const page=document.querySelector('#app .matrix-page');if(!page)return;page.classList.toggle('customized',state.mode==='custom');if(state.mode!=='custom')return;const data=saved(),timeNodes=times();page.style.setProperty('--customcols',data?.rows?.length||timeNodes.length);if(!data?.rows)return;const learningNodes=articles(),applicationNodes=[...document.querySelectorAll('#app .matrix-lane.application>article')],kept=new Set(data.rows.map((row,index)=>Number.isInteger(row.sourceIndex)?row.sourceIndex:index));data.rows.forEach((row,index)=>{const sourceIndex=Number.isInteger(row.sourceIndex)?row.sourceIndex:index;if(timeNodes[sourceIndex]&&row.time)timeNodes[sourceIndex].textContent=row.time;if(learningNodes[sourceIndex]&&row.learning){learningNodes[sourceIndex].classList.add('custom-learning');learningNodes[sourceIndex].innerHTML=row.learning.split(/\n+/).filter(Boolean).map(line=>`<p>${esc(line)}</p>`).join('')}});timeNodes.forEach((node,index)=>{if(!kept.has(index))node.parentElement.remove()});learningNodes.forEach((node,index)=>{if(!kept.has(index))node.remove()});applicationNodes.forEach((node,index)=>{if(!kept.has(index))node.remove()})}
  const app=document.querySelector('#app');if(app)new MutationObserver(()=>requestAnimationFrame(apply)).observe(app,{childList:true});
  function learningText(article){return[...(article?.children||[])].map(child=>child.innerText.replace(/\n+/g,'，').replace(/，+/g,'，').trim()).filter(Boolean).join('\n')}
  function editCard(row,index){return`<article class="timeline-edit-card" data-custom-row data-source-index="${row.sourceIndex}"><div class="timeline-edit-card-head"><i>${String(index+1).padStart(2,'0')}</i><strong>${esc(row.time)}</strong><button type="button" data-custom-remove title="删除此阶段" aria-label="删除${esc(row.time)}阶段">×</button></div><div class="timeline-edit-fields"><label><span>阶段时间</span><input data-custom-time value="${esc(row.time)}"></label><label><span>语言学习内容 <small>每行显示为一个信息块</small></span><textarea data-custom-learning>${esc(row.learning)}</textarea></label></div></article>`}
  function openEditor(){const timeNodes=times(),learningNodes=articles(),data=saved(),rows=data?.rows?.length?data.rows:timeNodes.map((node,index)=>({sourceIndex:index,time:node.textContent.trim(),learning:learningText(learningNodes[index])}));UI.modal(`<div class="timeline-editor"><div class="timeline-editor-head"><div><span class="timeline-editor-icon">✎</span><div><p class="section-kicker">PERSONAL TIMELINE</p><h2>编辑个性时间轴</h2><p class="muted">按学生实际起点调整阶段；不需要的阶段可直接删除。</p></div></div><span class="timeline-count"><b>${rows.length}</b> 个阶段</span></div><div class="timeline-editor-grid">${rows.map(editCard).join('')}</div><div class="timeline-editor-actions"><button class="btn custom-reset" data-custom-reset>↺ 恢复参考模板</button><span>修改仅保存在当前浏览器</span><div><button class="btn outline" data-close>取消</button><button class="btn primary" data-custom-save>✓ 保存并查看时间轴</button></div></div></div>`)}
  function renumberEditor(){const cards=[...document.querySelectorAll('[data-custom-row]')];cards.forEach((card,index)=>{card.querySelector('.timeline-edit-card-head>i').textContent=String(index+1).padStart(2,'0');card.querySelector('.timeline-edit-card-head>strong').textContent=card.querySelector('[data-custom-time]').value||`阶段 ${index+1}`});const count=document.querySelector('.timeline-count b');if(count)count.textContent=cards.length}
  document.addEventListener('input',event=>{if(event.target.hasAttribute('data-custom-time'))renumberEditor()});
  document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.customMode){state.mode=button.dataset.customMode;window.App?.render();return}if(button.hasAttribute('data-custom-edit')){openEditor();return}if(button.hasAttribute('data-custom-remove')){const cards=document.querySelectorAll('[data-custom-row]');if(cards.length<=1){window.App?.toast('至少保留一个规划阶段');return}button.closest('[data-custom-row]').remove();renumberEditor();return}if(button.hasAttribute('data-custom-save')){const rows=[...document.querySelectorAll('[data-custom-row]')].map(card=>({sourceIndex:Number(card.dataset.sourceIndex),time:card.querySelector('[data-custom-time]').value.trim(),learning:card.querySelector('[data-custom-learning]').value.trim()}));localStorage.setItem(key(),JSON.stringify({rows,updatedAt:new Date().toISOString()}));document.querySelector('#modalRoot').innerHTML='';state.mode='custom';window.App?.render();window.App?.toast(`个性时间轴已保存，共${rows.length}个阶段`);return}if(button.hasAttribute('data-custom-reset')){localStorage.removeItem(key());document.querySelector('#modalRoot').innerHTML='';state.mode='reference';window.App?.render();window.App?.toast('已恢复参考时间轴')}});
  window.CustomTimeline={state,key,saved};
})();
