(function(){
  const original=UI.studyPlan,state={mode:'reference',plan:null};
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function key(plan=state.plan){return`custom-timeline-${plan?.country||'DE'}-${plan?.scenario||'highschool'}-${plan?.route||'direct'}`}
  function saved(){try{const data=JSON.parse(localStorage.getItem(key())||'null');return data?.version===3?data:null}catch{return null}}
  function toolbar(){return`<div class="custom-timeline-tools"><div class="custom-mode-switch"><button class="${state.mode==='reference'?'active':''}" data-custom-mode="reference">参考时间轴</button><button class="${state.mode==='custom'?'active':''}" data-custom-mode="custom">个性时间轴</button></div><span class="custom-timeline-note">个性版本仅保存在当前浏览器</span><button class="custom-edit-button" data-custom-edit ${state.mode==='custom'?'':'hidden'}><span>✎</span>编辑个性规划</button></div>`}
  UI.studyPlan=plan=>{state.plan={...plan};const html=original(plan);return html.replace(/(<section class="matrix-page[^>]*>)/,`$1${toolbar()}`)};
  function laneArticles(type){return[...document.querySelectorAll(`#app .matrix-lane.${type}>article`)]}
  function articles(){return laneArticles('language')}
  function timeCells(){return[...document.querySelectorAll('#app .matrix-time>div')]}
  function times(){return timeCells().map(cell=>cell.querySelector('b')).filter(Boolean)}
  function textBlocks(article){return[...(article?.children||[])].map(child=>child.innerText.replace(/\n+/g,'，').replace(/，+/g,'，').trim()).filter(Boolean).join('\n')}
  function comparable(text){return String(text||'').normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,'')}
  function highlight(text){return esc(text).replace(/(JLPT|EJU|SGU|TOPIK|TestDaF|DSH|DELF|DALF|TCF|TEF|CELI|CILS|DELE|D-2|N[1-5]|T[1-6]|A[1-2]|B[1-2]|C[1-2])/gi,'<mark>$1</mark>')}
  function customArticle(source,text,type,edited){const article=source?source.cloneNode(true):document.createElement('article'),sameAsReference=source&&comparable(text)===comparable(textBlocks(source));article.classList.toggle('has-content',!!text);if(source&&(!edited||sameAsReference))return article;article.classList.add(type==='learning'?'custom-learning':'custom-application');article.innerHTML=text.split(/\n+/).filter(Boolean).map(line=>`<p>${highlight(line)}</p>`).join('');return article}
  function referenceRows(sourceTimes,sourceLearning,sourceApplication){return sourceTimes.map((cell,index)=>({sourceIndex:index,time:cell.querySelector('b')?.textContent.trim()||'',learning:textBlocks(sourceLearning[index]),application:textBlocks(sourceApplication[index])}))}
  function apply(){const page=document.querySelector('#app .matrix-page');if(!page)return;page.classList.toggle('customized',state.mode==='custom');if(state.mode!=='custom'||page.dataset.customApplied)return;page.dataset.customApplied='true';const data=saved(),sourceTimes=timeCells(),sourceLearning=laneArticles('language'),sourceApplication=laneArticles('application');state.referenceRows=referenceRows(sourceTimes,sourceLearning,sourceApplication);page.style.setProperty('--customcols',data?.rows?.length||sourceTimes.length);if(!data?.rows)return;const timeRow=document.querySelector('#app .matrix-time'),learningRow=document.querySelector('#app .matrix-lane.language'),applicationRow=document.querySelector('#app .matrix-lane.application');const newTimes=[],newLearning=[],newApplication=[];data.rows.forEach((row,index)=>{const sourceIndex=Number.isInteger(row.sourceIndex)?row.sourceIndex:null,sourceTime=sourceIndex===null?null:sourceTimes[sourceIndex],cell=sourceTime?sourceTime.cloneNode(true):document.createElement('div');if(!sourceTime)cell.innerHTML='<small></small><b></b>';const small=cell.querySelector('small'),label=cell.querySelector('b');if(small)small.textContent=String(index+1).padStart(2,'0');if(label)label.textContent=row.time||`阶段 ${index+1}`;newTimes.push(cell);const learning=row.learning??(sourceIndex===null?'':textBlocks(sourceLearning[sourceIndex])),application=row.application??(sourceIndex===null?'':textBlocks(sourceApplication[sourceIndex]));newLearning.push(customArticle(sourceIndex===null?null:sourceLearning[sourceIndex],learning,'learning',row.learningEdited||sourceIndex===null));newApplication.push(customArticle(sourceIndex===null?null:sourceApplication[sourceIndex],application,'application',row.applicationEdited||sourceIndex===null))});sourceTimes.forEach(node=>node.remove());sourceLearning.forEach(node=>node.remove());sourceApplication.forEach(node=>node.remove());newTimes.forEach(node=>timeRow.appendChild(node));newLearning.forEach(node=>learningRow.appendChild(node));newApplication.forEach(node=>applicationRow.appendChild(node))}
  const app=document.querySelector('#app');if(app)new MutationObserver(()=>requestAnimationFrame(apply)).observe(app,{childList:true});
  function learningText(article){return textBlocks(article)}
  function editCard(row,index){const sourceIndex=Number.isInteger(row.sourceIndex)?row.sourceIndex:'',added=sourceIndex==='';return`<article class="timeline-edit-card" data-custom-row data-source-index="${sourceIndex}" data-time-edited="${added||row.timeEdited?'1':'0'}" data-learning-edited="${added||row.learningEdited?'1':'0'}" data-application-edited="${added||row.applicationEdited?'1':'0'}"><div class="timeline-edit-card-head"><i>${String(index+1).padStart(2,'0')}</i><strong>${esc(row.time)}</strong><button type="button" data-custom-remove title="删除此阶段" aria-label="删除${esc(row.time)}阶段">×</button></div><div class="timeline-edit-fields"><label><span>阶段时间</span><input data-custom-time value="${esc(row.time)}"></label><label><span>语言学习内容 <small>每行一个信息块</small></span><textarea data-custom-learning>${esc(row.learning)}</textarea></label><label><span>留学规划内容 <small>每行一个信息块</small></span><textarea data-custom-application>${esc(row.application)}</textarea></label></div></article>`}
  function openEditor(){const data=saved(),references=state.referenceRows||referenceRows(timeCells(),articles(),laneArticles('application')),rows=data?.rows?.length?data.rows.map((row,index)=>{const sourceIndex=Number.isInteger(row.sourceIndex)?row.sourceIndex:index,reference=references[sourceIndex]||{};return{...reference,...row,sourceIndex:Number.isInteger(row.sourceIndex)?row.sourceIndex:null,application:row.application??reference.application??''}}):references;UI.modal(`<div class="timeline-editor"><div class="timeline-editor-head"><div><span class="timeline-editor-icon">✎</span><div><p class="section-kicker">PERSONAL TIMELINE</p><h2>编辑个性时间轴</h2><p class="muted">时间、语言学习与留学规划均可修改；新增或删除会同步整列。</p></div></div><span class="timeline-count"><b>${rows.length}</b> 个阶段</span></div><div class="timeline-editor-grid">${rows.map(editCard).join('')}</div><div class="timeline-editor-actions"><button class="btn custom-reset" data-custom-reset>↺ 恢复参考模板</button><button class="btn outline custom-add" data-custom-add>＋ 新增阶段</button><span>修改仅保存在当前浏览器</span><div><button class="btn outline" data-close>取消</button><button class="btn primary" data-custom-save>✓ 保存并查看时间轴</button></div></div></div>`)}
  function renumberEditor(){const cards=[...document.querySelectorAll('[data-custom-row]')];cards.forEach((card,index)=>{card.querySelector('.timeline-edit-card-head>i').textContent=String(index+1).padStart(2,'0');card.querySelector('.timeline-edit-card-head>strong').textContent=card.querySelector('[data-custom-time]').value||`阶段 ${index+1}`});const count=document.querySelector('.timeline-count b');if(count)count.textContent=cards.length}
  document.addEventListener('input',event=>{const card=event.target.closest('[data-custom-row]');if(!card)return;if(event.target.hasAttribute('data-custom-time')){card.dataset.timeEdited='1';renumberEditor()}else if(event.target.hasAttribute('data-custom-learning'))card.dataset.learningEdited='1';else if(event.target.hasAttribute('data-custom-application'))card.dataset.applicationEdited='1'});
  document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.customMode){state.mode=button.dataset.customMode;window.App?.render();return}if(button.hasAttribute('data-custom-edit')){openEditor();return}if(button.hasAttribute('data-custom-add')){const grid=document.querySelector('.timeline-editor-grid'),index=document.querySelectorAll('[data-custom-row]').length;grid.insertAdjacentHTML('beforeend',editCard({sourceIndex:null,time:`阶段 ${index+1}`,learning:'',application:''},index));renumberEditor();grid.scrollTo({top:grid.scrollHeight,behavior:'smooth'});return}if(button.hasAttribute('data-custom-remove')){const cards=document.querySelectorAll('[data-custom-row]');if(cards.length<=1){window.App?.toast('至少保留一个规划阶段');return}button.closest('[data-custom-row]').remove();renumberEditor();return}if(button.hasAttribute('data-custom-save')){const rows=[...document.querySelectorAll('[data-custom-row]')].map(card=>({sourceIndex:card.dataset.sourceIndex===''?null:Number(card.dataset.sourceIndex),time:card.querySelector('[data-custom-time]').value.trim(),learning:card.querySelector('[data-custom-learning]').value.trim(),application:card.querySelector('[data-custom-application]').value.trim(),timeEdited:card.dataset.timeEdited==='1',learningEdited:card.dataset.learningEdited==='1',applicationEdited:card.dataset.applicationEdited==='1'}));localStorage.setItem(key(),JSON.stringify({version:3,rows,updatedAt:new Date().toISOString()}));document.querySelector('#modalRoot').innerHTML='';state.mode='custom';window.App?.render();window.App?.toast(`个性时间轴已保存，共${rows.length}个阶段`);return}if(button.hasAttribute('data-custom-reset')){localStorage.removeItem(key());document.querySelector('#modalRoot').innerHTML='';state.mode='reference';window.App?.render();window.App?.toast('已恢复参考时间轴')}});
  window.CustomTimeline={state,key,saved};
})();
