(function(){
const base=UI.studyPlan,countries=[['JP','🇯🇵','日本'],['KR','🇰🇷','韩国'],['DE','🇩🇪','德国'],['FR','🇫🇷','法国'],['IT','🇮🇹','意大利'],['ES','🇪🇸','西班牙'],['RU','🇷🇺','俄罗斯']];
const shared=[
['高一上','秋季周末/晚班：韩语T1阶段学习，180课时，每周6-10小时；寒假：复习巩固T1阶段内容，强化基础词汇、语法、听力及口语','明确韩国本科留学意向；了解韩国本科升学路径、院校及专业方向；保持高中在校成绩；寒假可参加课外活动及兴趣探索，初步了解专业方向'],
['高一下','春季周末/晚班：韩语T2阶段学习，180课时，每周6-10小时；暑假全日制：韩语T3阶段学习，180课时，周一至周五每天约4小时','进一步探索专业方向；了解韩国大学及专业特点；保持高中在校成绩；暑假可参加竞赛、实践、科研、实习等背景提升活动，进一步明确专业方向'],
['高二上','秋季周末/晚班：韩语T4阶段学习，180课时，每周6-10小时，开始了解TOPIK题型；寒假：巩固T4阶段内容，逐步接触TOPIK专项题型及模考','根据在校成绩、专业方向及语言进度初步选校；建立冲刺、匹配、保底院校梯度；了解目标院校语言要求；寒假进一步了解目标院校招生要求，梳理个人学术及活动背景'],
['高二下','春季周末/晚班：韩语T5阶段学习，180课时，每周6-10小时，加入TOPIK专项训练及模考；暑假全日制：韩语T6阶段学习，180课时，周一至周五每天约4小时，强化TOPIK训练，建议开始参加TOPIK考试','进一步确定目标院校及专业；核对申请资格、语言要求及材料要求；暑假基本确定申请院校及专业梯度，提前规划文书，梳理成绩单、证明、公证/认证等申请材料']];
const plans={direct:{name:'秋季9月入学',label:'高中毕业当年9月',items:[...shared,
['高三上','TOPIK集中备考约120课时，每周6-10小时；参加TOPIK考试并持续刷分；寒假未达到目标等级继续备考及刷分','最终确定申请院校及专业；准备个人陈述、学业计划书等文书；整理完整申请材料；寒假完成材料检查、翻译、公证/认证等事项，重点关注秋季招生简章及申请开放时间'],['高三下3-6月','继续TOPIK刷分；根据目标院校要求提交或补充语言成绩','进入9月秋季入学申请期；陆续完成网申、申请费缴纳及材料递交；根据院校要求参加面试/校考；跟进补件及申请进度'],['高三下6-7月','加强生活韩语及学术韩语，为韩国大学学习做准备','陆续查询录取结果；确定最终入学院校；缴纳学费；申请宿舍；准备标准入学许可及签证材料'],['毕业7-8月','进行赴韩前生活韩语及学术韩语强化','获取标准入学许可；办理D-2留学签证；完成行前指导；准备住宿、机票、保险及入境材料'],['毕业当年9月','进入韩国大学后的韩语及专业课程学习','赴韩报到；完成注册及入学手续；正式进入韩国本科']]},prep:{name:'次年3月入学',label:'高中毕业次年3月',items:[...shared.slice(0,3),
['高二下','春季周末/晚班：韩语T5阶段学习，180课时，每周6-10小时，加入TOPIK专项训练及模考；暑假全日制：韩语T6阶段学习，180课时，周一至周五每天约4小时，强化TOPIK训练，建议开始参加TOPIK考试','进一步确定目标院校及专业；核对申请资格、语言要求；暑假基本确定申请院校及专业方向，提前规划文书及申请材料'],['高三上','TOPIK集中备考约120课时，每周6-10小时；参加TOPIK考试并持续刷分；寒假根据成绩继续强化及刷分','进一步明确申请院校及专业梯度；保持高中在校成绩；提前梳理申请材料；寒假准备个人陈述、学业计划书等文书，并了解目标院校春季招生要求'],['高三下','继续TOPIK备考及刷分，争取取得更有竞争力的语言成绩','完成高中阶段学业；最终确定次年3月入学申请方案；持续完善文书及申请材料；提前准备毕业后申请所需材料'],['毕业6-8月','TOPIK集中强化及刷分；争取在正式申请前取得符合目标院校要求的语言成绩','取得高中毕业证及完整成绩单；最终确定申请院校及专业；集中完成文书、翻译、公证/认证等申请材料'],['毕业8-11月','根据目标院校要求继续参加TOPIK考试或补充语言成绩','进入次年3月春季入学申请期；陆续完成网申、申请费缴纳及材料递交；根据院校要求参加面试/校考；跟进补件及申请进度'],['11月-次年1月','保持韩语学习；加强学术韩语及大学学习场景韩语','陆续查询录取结果；确定最终入学院校；缴纳学费；申请宿舍；准备标准入学许可及签证材料'],['次年1-2月','进行赴韩前生活韩语及学术韩语强化','获取标准入学许可；办理D-2留学签证；完成行前指导；准备住宿、机票、保险及入境材料'],['毕业次年3月','进入韩国大学后的韩语及专业课程学习','赴韩报到；完成注册及入学手续；正式进入韩国本科']]}};
function chunks(s){return s.split('；').filter(Boolean).map(t=>`<p>${t.replace(/(T[1-6]|TOPIK|D-2|\d+课时|每周6-10小时|每天约4小时)/g,'<mark>$1</mark>')}</p>`).join('')}
function korea(state){let p=plans[state.route]||plans.direct,n=p.items.length;return`<section class="matrix-page kr-compact" style="--krcols:${n}"><header class="matrix-title"><div><p class="section-kicker">KOREA UNDERGRADUATE ROADMAP</p><h2>韩国高中生申请本科规划</h2></div><div class="matrix-countries">${countries.map(c=>`<button class="${c[0]==='KR'?'active':''}" data-plan-country="${c[0]}">${c[1]} ${c[2]}</button>`).join('')}</div></header><div class="kr-compact-top"><div><span>申请身份</span><b>高中生申请本科</b><small>国内普高 · 高一开始规划</small></div><div class="kr-compact-routes"><span>选择入学季</span>${Object.entries(plans).map(([id,x])=>`<button class="${state.route===id?'active':''}" data-plan-route="${id}"><i>${id==='direct'?'09':'03'}</i><b>${x.name}</b><small>${x.label}</small></button>`).join('')}</div></div><div class="matrix-shell"><div class="kr-era"><strong>规划阶段</strong><div>高考前 · 语言与背景建设</div><div>高考后 · 申请与入学执行</div></div><div class="matrix-grid matrix-time"><strong>时间</strong>${p.items.map((x,i)=>`<div class="${i<4?'language':i===4?'decision':'apply'}"><small>${String(i+1).padStart(2,'0')}</small><b>${x[0]}</b></div>`).join('')}</div><div class="matrix-grid matrix-lane language"><strong><i>语</i>语言学习</strong>${p.items.map((x,i)=>`<article class="${i<4?'language':i===4?'decision':'apply'}">${chunks(x[1])}</article>`).join('')}</div><div class="matrix-grid matrix-lane application"><strong><i>申</i>留学节点</strong>${p.items.map((x,i)=>`<article class="${i<4?'language':i===4?'decision':'apply'} has-content">${chunks(x[2])}</article>`).join('')}</div></div><footer class="matrix-note"><b>${p.name}</b> · 共${n}个阶段；从左到右依次推进。<span>具体要求以韩国院校及官方最新政策为准。</span></footer></section>`}
UI.studyPlan=state=>state?.country==='KR'&&(!state.scenario||state.scenario==='highschool')?korea(state):base(state);
})();
