(function(){
  const flags={日语:'🇯🇵',韩语:'🇰🇷',德语:'🇩🇪',法语:'🇫🇷',西班牙语:'🇪🇸',意大利语:'🇮🇹',俄语:'🇷🇺'};
  const nodeLabels={'报名注册开始':'即将开始报名注册','正式报名开始':'即将正式开始报名','正式报名截止':'报名即将截止','考试日期':'考试时间正式公布','出分日期':'成绩即将公布'};
  const scoreTemplates={topik:'assets/topik-score-template.jpg',testdaf:'assets/testdaf-score-template.jpg',jlpt:'assets/jlpt-score-template.jpg'};
  const testdafRegistrationTemplate='assets/testdaf-registration-template.png';
  const topikKoreaRegistrationTemplate='assets/topik-korea-registration-template.png';
  const jlptRegistrationTemplate='assets/jlpt-registration-template.jpg';
  function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
  function fmt(v){const d=DateUtils.parseExcelDate(v);return d?`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日`:'待官方公布'}
  function wrap(c,text,x,y,w,lineHeight,max=99,align='left'){const chars=String(text||'').split(''),out=[];let line='';for(const ch of chars){if(ch==='\n'){out.push(line);line='';continue}if(c.measureText(line+ch).width>w&&line){out.push(line);line=ch}else line+=ch}if(line)out.push(line);c.textAlign=align;out.slice(0,max).forEach((v,i)=>c.fillText(v,x,y+i*lineHeight));c.textAlign='left';return Math.min(out.length,max)*lineHeight}
  function fitTitle(c,text,x,y,w,maxLines=3){let size=66;while(size>=44){c.font=`900 ${size}px "PingFang SC","Microsoft YaHei",sans-serif`;const chars=String(text).split('');let lines=1,line='';for(const ch of chars){if(c.measureText(line+ch).width>w&&line){lines++;line=ch}else line+=ch}if(lines<=maxLines)return wrap(c,text,x,y,w,size*1.18,maxLines,'center');size-=4}return wrap(c,text,x,y,w,54,maxLines,'center')}
  function rows(s){return[['报名注册开始',s.registrationStart],['正式报名开始',s.applicationStart],['正式报名截止',s.applicationDeadline],['考试日期',s.examDate],['出分日期',s.scoreDate]].filter(v=>v[1])}
  function scoreTemplateType(event){if(event.eventType!=='出分日期')return'';const id=String(event.examId||''),name=String(event.examName||'');if(id==='JP-JLPT'||/JLPT|日本语能力/i.test(name))return'jlpt';if(id==='KR-TOPIK'||/TOPIK/i.test(name))return'topik';if(id==='DE-德福'||/TestDaF|德福/i.test(name))return'testdaf';return''}
  function isTestdafRegistrationPoster(event){const id=String(event.examId||''),name=String(event.examName||''),node=String(event.eventType||'');return(id==='DE-TestDaF'||id==='DE-德福'||/TestDaF|德福/i.test(name))&&['报名注册开始','正式报名开始','正式报名截止','考试日期'].includes(node)}
  function isTopikKoreaRegistrationPoster(event){const s=event.session||{},id=String(event.examId||''),name=String(event.examName||''),region=`${s.region||''}${s.sessionName||''}${s.notes||''}`,node=String(event.eventType||'');return(id==='KR-TOPIK'||/TOPIK/i.test(name))&&/韩国/.test(region)&&['报名注册开始','正式报名开始','正式报名截止','准考证打印开始','考试日期'].includes(node)}
  function isJlptRegistrationPoster(event){const id=String(event.examId||''),name=String(event.examName||''),node=String(event.eventType||'');return(id==='JP-JLPT'||/JLPT|日本语能力/i.test(name))&&['报名注册开始','正式报名开始','正式报名截止','准考证打印开始','考试日期'].includes(node)}
  function drawDateBadge(c,date){const d=DateUtils.parseExcelDate(date)||new Date();c.fillStyle='#ef665f';c.fillRect(746,248,109,141);c.fillStyle='#fff';c.textAlign='center';c.font='500 52px Arial,sans-serif';c.fillText(String(d.getDate()).padStart(2,'0'),800.5,315);c.fillStyle='rgba(255,255,255,.72)';c.fillRect(759,327,83,2);c.font='700 27px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${String(d.getMonth()+1).padStart(2,'0')}月`,800.5,371);c.textAlign='left'}
  function plainDate(v){const d=DateUtils.parseExcelDate(v);return d?`${d.getFullYear()}.${d.getMonth()+1}.${d.getDate()}`:'待官方公布'}
  function cnDate(v){const d=DateUtils.parseExcelDate(v);return d?`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日`:'以官方通知为准'}
  function monthDay(v){const d=DateUtils.parseExcelDate(v);return d?`${d.getMonth()+1}月${d.getDate()}日`:'以官方通知为准'}
  function daysBefore(v,count){const d=DateUtils.parseExcelDate(v);if(!d)return'';const out=new Date(d);out.setDate(out.getDate()-count);return out}
  function topikEdition(s){const m=String(s.sessionName||'').match(/第\s*(\d+)\s*届/);return m?m[1]:String(s.year||new Date().getFullYear())}
  function jlptSessionMonth(s,event){const explicit=Number(s.sessionMonth),match=String(s.sessionName||'').match(/(\d{1,2})月/),exam=DateUtils.parseExcelDate(s.examDate);return explicit||(match&&Number(match[1]))||(exam&&exam.getMonth()+1)||Number(event.month)||''}
  function drawJlptDateBadge(c,date){const d=DateUtils.parseExcelDate(date)||new Date();c.fillStyle='#ec635c';c.fillRect(774,267,112,144);c.fillStyle='#fff';c.textAlign='center';c.font='500 52px Arial,sans-serif';c.fillText(String(d.getDate()).padStart(2,'0'),830,326);c.fillStyle='rgba(255,255,255,.65)';c.fillRect(790,346,80,2);c.font='700 27px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${String(d.getMonth()+1).padStart(2,'0')}月`,830,386);c.textAlign='left'}
  function drawTopikKoreaDateBadge(c,date){const d=DateUtils.parseExcelDate(date)||new Date();c.fillStyle='#ef665f';c.fillRect(774,252,112,146);c.fillStyle='#fff';c.textAlign='center';c.font='500 52px Arial,sans-serif';c.fillText(String(d.getDate()).padStart(2,'0'),830,318);c.fillStyle='rgba(255,255,255,.72)';c.fillRect(790,331,80,2);c.font='700 27px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${String(d.getMonth()+1).padStart(2,'0')}月`,830,375);c.textAlign='left'}
  function drawJlptRegistrationDateBadge(c,date){const d=DateUtils.parseExcelDate(date)||new Date();c.fillStyle='#ef665f';c.fillRect(744,246,111,145);c.fillStyle='#fff';c.textAlign='center';c.font='500 54px Arial,sans-serif';c.fillText(String(d.getDate()).padStart(2,'0'),800,313);c.fillStyle='rgba(255,255,255,.72)';c.fillRect(758,329,83,2);c.font='700 28px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${String(d.getMonth()+1).padStart(2,'0')}月`,800,374);c.textAlign='left'}
  async function createJlptScorePoster(event){const s=event.session||{},base=await loadImage(scoreTemplates.jlpt),canvas=document.createElement('canvas');canvas.width=base.naturalWidth;canvas.height=base.naturalHeight;const c=canvas.getContext('2d'),red='#c9002d',ink='#171717',blue='#1471c9',month=jlptSessionMonth(s,event),scoreDate=DateUtils.parseExcelDate(s.scoreDate||event.eventDate),year=Number(s.year||event.year||(scoreDate&&scoreDate.getFullYear())||new Date().getFullYear()),scoreText=scoreDate?`${scoreDate.getMonth()+1}月${scoreDate.getDate()}日11:00`:'官方公布当日11:00';c.drawImage(base,0,0);
    drawJlptDateBadge(c,new Date());
    // 红色模板的顶部、日期牌、人物及底部品牌区保持原样，只重绘白色正文内部。
    c.fillStyle='#fff';c.fillRect(62,525,1001,1655);c.textAlign='center';c.fillStyle=red;c.font='900 62px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${month?`${month}月`:''}JLPT查分通知`,562,652);c.fillStyle='#d9bfc5';c.fillRect(96,708,932,2);c.textAlign='left';
    c.fillStyle=ink;c.font='500 32px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('考生注意啦：能力考成绩查询通知已出！！！',92,786);c.fillText(`北京时间${scoreText} 将开通查询入口：`,92,866);c.fillText('教育网查询入口：',92,946);c.fillStyle=blue;c.font='italic 30px Arial,sans-serif';c.fillText('https://jlpt.neea.edu.cn/qryscore.jsp',337,946);c.fillStyle=ink;c.font='500 32px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('公网查询入口：',92,1025);c.fillStyle=blue;c.font='italic 30px Arial,sans-serif';c.fillText('https://jlpt.neea.cn/qryscore.jsp',337,1025);c.fillStyle=ink;c.font='600 32px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('祝大家都能得到理想的「合格」！！！！',92,1112);
    const boxX=92,boxY=1180,boxW=940,boxH=870;c.fillStyle='#f1f1f1';c.fillRect(boxX,boxY,boxW,boxH);c.strokeStyle='#202020';c.lineWidth=2;c.strokeRect(boxX,boxY,boxW,boxH);c.textAlign='center';c.fillStyle='#c43b77';c.font='700 25px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${year}年${month?`${month}月`:''}日本语能力测试成绩查询相关安排`,562,1234);c.textAlign='left';c.fillStyle=ink;c.font='500 24px "PingFang SC","Microsoft YaHei",sans-serif';let y=1300;y+=wrap(c,`根据考试主办方日本国际交流基金会安排，${year}年${month?`${month}月`:''}日本语能力测试（JLPT）成绩发布时间为${scoreDate?`${scoreDate.getMonth()+1}月${scoreDate.getDate()}日`:'官方公布日期'}，具体如下：`,128,y,865,38,4);y+=24;c.font='700 26px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('一、查询网址',128,y);y+=54;c.font='500 24px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('教育网查询入口：https://jlpt.neea.edu.cn/qryscore.jsp',158,y);y+=46;c.fillText('公网查询入口：https://jlpt.neea.cn/qryscore.jsp',158,y);y+=46;c.fillText(`以上两种方式均可查询，开通时间为${scoreText.replace(':00','时')}。`,158,y);y+=66;c.font='700 26px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('二、查询方式',128,y);y+=54;c.font='500 24px "PingFang SC","Microsoft YaHei",sans-serif';y+=wrap(c,'凭本次考试准考证号和报名时注册的有效身份证件号码进行查询。',158,y,815,38,3);y+=24;c.font='600 23px "PingFang SC","Microsoft YaHei",sans-serif';wrap(c,'说明：网上查询的成绩仅供参考，最终成绩以证书和成绩单为准。证书和成绩单约在考试后三个月到达考点，考生可根据考点安排领取。',158,y,815,37,5);c.textAlign='left';return canvas}
  async function createScorePoster(event,type){const s=event.session||{},base=await loadImage(scoreTemplates[type]),canvas=document.createElement('canvas');canvas.width=base.naturalWidth;canvas.height=base.naturalHeight;const c=canvas.getContext('2d'),red='#c9002d',ink='#171717';c.drawImage(base,0,0);drawDateBadge(c,new Date());
    c.textAlign='center';c.fillStyle='#fff';c.fillRect(54,548,1017,type==='topik'?168:246);c.fillStyle=red;
    if(type==='testdaf'){c.font='800 55px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${s.year||event.year||new Date().getFullYear()}年中国大陆地区德福考试`,562,660);c.fillText('（TESTDAF）查分攻略',562,746);c.fillStyle='#fff';c.fillRect(105,3390,915,120);c.fillStyle=ink;c.font='700 31px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('祝福考生们都能取得理想的成绩，期待听到大家的好消息！！！！',562,3470)}
    else{c.font='800 61px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${topikEdition(s)}届TOPIK考试查分通知`,562,669);c.textAlign='left';c.fillStyle='#fff';c.fillRect(94,742,900,108);c.fillStyle=ink;c.font='500 35px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`考试时间： ${plainDate(s.examDate)}`,98,781);c.fillText(`成绩公布： ${plainDate(s.scoreDate||event.eventDate)} 15:00(北京时间)`,98,837)}
    c.textAlign='left';return canvas}
  async function createTestdafRegistrationPoster(event){const s=event.session||{},base=await loadImage(testdafRegistrationTemplate),canvas=document.createElement('canvas');canvas.width=base.naturalWidth;canvas.height=base.naturalHeight;const c=canvas.getContext('2d'),red='#c9002d',ink='#111',soft='#fff0f3',muted='#d3d5d7',exam=DateUtils.parseExcelDate(s.examDate),registration=s.registrationStart,application=s.applicationStart,deadline=s.applicationDeadline,year=Number(s.year||event.year||(exam&&exam.getFullYear())||new Date().getFullYear()),month=Number(s.sessionMonth||(exam&&exam.getMonth()+1)||event.month||'');c.drawImage(base,0,0);drawDateBadge(c,new Date());
    // 固定沿用参考海报，只重绘白色考试信息区域内允许变化的节点数据。
    c.fillStyle='#fff';c.fillRect(54,568,1017,2110);c.textAlign='center';c.fillStyle=red;c.font='900 55px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${year}年${month?`${month}月`:''}德福考试（TESTDAF）`,562,675);const firstStart=registration||application;c.fillText(firstStart?`将于${monthDay(firstStart)}开始注册报名`:'注册报名时间以官方通知为准',562,748);c.fillStyle='#e7c7ce';c.fillRect(91,798,944,2);c.textAlign='left';c.fillStyle=ink;c.font='500 30px "PingFang SC","Microsoft YaHei",sans-serif';let introY=872;introY+=wrap(c,`经与考试主办方协商，${year}年${month?`${month}月`:''}德福考试（TestDaF）报名工作安排如下：`,104,introY,900,43,3);
    const section=(title,y,h)=>{const g=c.createLinearGradient(92,y,1018,y);g.addColorStop(0,red);g.addColorStop(1,'#f4c8d2');c.fillStyle=g;c.fillRect(92,y,930,57);c.fillStyle=soft;c.fillRect(92,y+57,930,h-57);c.fillStyle='#fff';c.font='800 32px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(title,111,y+40);return y+102};
    const bullet=(text,y,maxLines=3,color=ink,font='500 29px "PingFang SC","Microsoft YaHei",sans-serif')=>{c.fillStyle=muted;c.beginPath();c.arc(126,y-9,7,0,Math.PI*2);c.fill();c.fillStyle=color;c.font=font;return y+wrap(c,text,153,y,825,42,maxLines)};
    let y=Math.max(948,introY+24),body=section('一、考试时间：',y,245);body=bullet(`笔试：${cnDate(s.examDate)}8:30—12:00`,body);body=bullet(`口试：${cnDate(s.examDate)}下午`,body+12);y+=270;
    body=section('二、报名网址：',y,245);body=bullet('http://testdaf.neea.cn/',body,1,'#145fe0','500 29px Arial,sans-serif');body=bullet('http://testdaf.neea.edu.cn/',body+10,1,'#145fe0','500 29px Arial,sans-serif');y+=270;
    body=section('三、报名时间：',y,330);body=bullet(registration&&deadline?`${cnDate(registration)}14:00—${monthDay(deadline)}14:00，注册个人信息并上传电子照片。`:'个人信息注册时间：以官方最新通知为准。',body,3);body=bullet(application&&deadline?`${cnDate(application)}14:00—${monthDay(deadline)}14:00，预定考位并支付考试费用。`:'预定考位及缴费时间：以官方最新通知为准。',body+14,3);y+=355;
    const centerText=String(s.examCenter||'具体考点以德福考试报名网站“考点信息”最新公布为准。').replace(/^https?:\/\/\S+\s*[（(]?详见考点信息[）)]?$/,'具体考点请查看德福考试报名网站“考点信息”。');body=section('四、考点信息：',y,355);bullet(centerText,body,6);y+=380;
    body=section('五、准考证打印起止时间：',y,210);const printStart=s.ticketPrintStart||daysBefore(s.examDate,5),printEnd=s.ticketPrintEnd||s.examDate,printText=printStart&&printEnd?`${cnDate(printStart)}14:00—${monthDay(printEnd)}17:00`:'以官方最新通知为准';bullet(printText,body,2);c.textAlign='left';return canvas}
  function shortCnDate(v){const d=DateUtils.parseExcelDate(v);return d?`${String(d.getFullYear()).slice(-2)}年${d.getMonth()+1}月${d.getDate()}日`:'以官方通知为准'}
  function compactTime(v){return String(v||'').replace(/\s+/g,'').replace(/点(整)?$/,'点')}
  function topikKoreaTitle(event,s){const d=DateUtils.parseExcelDate(event.eventDate),date=d?`${d.getMonth()+1}月${d.getDate()}日`:'';if(event.eventType==='准考证打印开始'){const print=compactTime(s.noteTicketPrint).split(/[-–—~～至]/)[0]||date;return`${topikEdition(s)}届TOPIK韩国场准考证\n将于${print||'官方指定日期'}开始打印`}if(event.eventType==='正式报名截止'){const deadline=compactTime(s.noteRegistrationDeadline)||date;return`${topikEdition(s)}届TOPIK韩国场报名将于\n${deadline||'官方指定日期'}截止`}if(event.eventType==='考试日期')return`${topikEdition(s)}届TOPIK韩国场考试将于\n${date||'官方指定日期'}举行`;const registration=compactTime(s.noteRegistrationTime)||date;return`${topikEdition(s)}届TOPIK韩国场报名将于\n${registration||'官方指定日期'}开始`}
  async function createTopikKoreaRegistrationPoster(event){const s=event.session||{},base=await loadImage(topikKoreaRegistrationTemplate),canvas=document.createElement('canvas');canvas.width=base.naturalWidth;canvas.height=base.naturalHeight;const c=canvas.getContext('2d'),red='#c9002d',ink='#111';c.drawImage(base,0,0);drawTopikKoreaDateBadge(c,new Date());
    // 参考海报的品牌区、报名网站、注意事项和底部信息保持不变。
    c.fillStyle='#fff';c.fillRect(54,600,1017,270);c.textAlign='center';c.fillStyle=red;c.font='900 57px "PingFang SC","Microsoft YaHei",sans-serif';wrap(c,topikKoreaTitle(event,s),562,685,930,72,3,'center');
    c.fillStyle='#fff';c.fillRect(83,1030,960,555);c.textAlign='left';c.fillStyle=ink;c.font='800 31px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('二、考试日程',89,1068);c.fillStyle=red;c.font='800 29px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`考试日期：${shortCnDate(s.examDate)}`,89,1120);c.fillText(`打印准考证：${s.noteTicketPrint||'以官方通知为准'}`,89,1170);c.fillText(`成绩公布：${s.noteScoreTime||(s.scoreDate?monthDay(s.scoreDate):'以官方通知为准')}`,89,1220);
    c.fillStyle=ink;c.font='800 31px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('三、报名日程',89,1272);c.font='600 28px "PingFang SC","Microsoft YaHei",sans-serif';const registrationLine=s.noteRegistrationTime?`报名时间：${s.noteRegistrationTime}\n`:'';wrap(c,`${registrationLine}${s.examCenter||'请以表格“考点信息”字段为准。'}`,89,1322,930,43,6);c.textAlign='left';return canvas}
  function jlptTitle(event,s){const exam=DateUtils.parseExcelDate(s.examDate),year=Number(s.year||(exam&&exam.getFullYear())||new Date().getFullYear()),month=jlptSessionMonth(s,event),prefix=`${String(year).slice(-2)}年${month}月日语能力考`,date=monthDay(event.eventDate);if(event.eventType==='报名注册开始')return`${prefix}${date}注册！\n${monthDay(s.applicationStart)}早上7点开始报名！`;if(event.eventType==='正式报名开始')return`${prefix}\n${date}早上7点开始报名！`;if(event.eventType==='正式报名截止')return`${prefix}报名将于\n${date}14点截止！`;if(event.eventType==='准考证打印开始')return`${prefix}准考证\n${String(s.noteTicketPrint||date).split(/[-–—~～至]/)[0]}开始打印！`;return`${prefix}\n${date}正式开考！`}
  async function createJlptRegistrationPoster(event){const s=event.session||{},base=await loadImage(jlptRegistrationTemplate),canvas=document.createElement('canvas');canvas.width=base.naturalWidth;canvas.height=base.naturalHeight;const c=canvas.getContext('2d'),red='#c9002d',ink='#171717',exam=DateUtils.parseExcelDate(s.examDate),month=jlptSessionMonth(s,event);c.drawImage(base,0,0);drawJlptRegistrationDateBadge(c,new Date());
    c.fillStyle='#fff';c.fillRect(54,580,1017,180);c.textAlign='center';c.fillStyle=red;c.font='900 52px "PingFang SC","Microsoft YaHei",sans-serif';wrap(c,jlptTitle(event,s),562,635,930,68,3,'center');
    c.fillStyle='#fff';c.fillRect(82,760,950,76);c.textAlign='left';c.fillStyle=ink;c.font='500 27px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${s.year||exam?.getFullYear()||''}年${month}月日本语能力测试（JLPT）报名有关安排如下：`,96,812);
    // 一、二仅替换考试日期；原表格、两条注释和底纹水印完整保留。
    c.fillStyle='#fff';c.fillRect(92,880,330,58);c.textAlign='left';c.fillStyle=ink;c.font='600 30px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(cnDate(s.examDate),96,925);
    c.fillStyle='#fff';c.fillRect(103,1142,72,260);c.fillStyle=ink;c.font='700 29px "PingFang SC","Microsoft YaHei",sans-serif';wrap(c,`${month}月${exam?exam.getDate():''}日`,139,1215,38,42,4,'center');c.textAlign='left';
    // 四、五只局部覆盖日期文字，不重绘其他内容。
    c.fillStyle='#fff';c.fillRect(420,1830,600,112);c.fillStyle=red;c.font='800 29px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${monthDay(s.registrationStart)}7:00至${monthDay(s.applicationDeadline)}14:00`,445,1870);c.fillText(`${monthDay(s.applicationStart)}7:00至${monthDay(s.applicationDeadline)}14:00`,445,1925);
    c.fillStyle='#fff';c.fillRect(505,1958,535,82);c.fillStyle='#ffdf32';c.fillRect(515,1972,505,54);c.fillStyle=ink;c.font='800 28px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(s.noteTicketPrint||'以官方最新通知为准',530,2009);c.textAlign='left';return canvas}
  async function create(event){const scoreType=scoreTemplateType(event);if(scoreType)return scoreType==='jlpt'?createJlptScorePoster(event):createScorePoster(event,scoreType);if(isJlptRegistrationPoster(event))return createJlptRegistrationPoster(event);if(isTopikKoreaRegistrationPoster(event))return createTopikKoreaRegistrationPoster(event);if(isTestdafRegistrationPoster(event))return createTestdafRegistrationPoster(event);const s=event.session||{},base=await loadImage(window.POSTER_TEMPLATE_DATA||'assets/shinyway-info-template.jpg'),canvas=document.createElement('canvas');canvas.width=base.naturalWidth||1125;canvas.height=base.naturalHeight||2656;const c=canvas.getContext('2d'),red='#c9002d',ink='#141414';c.drawImage(base,0,0,canvas.width,canvas.height);
    // 原模板只替换日期牌内的数字。
    c.fillStyle='#ec635c';c.fillRect(774,267,112,144);const d=new Date();c.fillStyle='#fff';c.textAlign='center';c.font='500 52px sans-serif';c.fillText(String(d.getDate()).padStart(2,'0'),830,326);c.fillStyle='rgba(255,255,255,.65)';c.fillRect(790,346,80,2);c.fillStyle='#fff';c.font='700 27px sans-serif';c.fillText(`${String(d.getMonth()+1).padStart(2,'0')}月`,830,386);c.textAlign='left';
    // 覆盖原模板白色正文，仅动态填入本场考试数据。
    c.fillStyle='#fff';c.fillRect(60,523,1005,1660);let y=612;const sessionPrefix=s.sessionName||`${s.year||''}年${s.sessionMonth?`${s.sessionMonth}月`:''}场`,title=`${sessionPrefix}${event.examName}\n${nodeLabels[event.eventType]||event.eventType}`;c.fillStyle=red;y+=fitTitle(c,title,562,y,880,3)+20;c.fillStyle='#d1bfc2';c.fillRect(95,y,935,2);y+=75;
    c.fillStyle=ink;c.font='800 34px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('一、考试信息',95,y);y+=58;c.font='500 30px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${flags[event.language]||'🌐'} 语种：${event.language||'其他'}`,108,y);y+=49;c.fillText(`考试名称：${event.examName}`,108,y);y+=49;y+=wrap(c,`考试场次：${s.sessionName||'以官方最新通知为准'}`,108,y,870,44,2);y+=36;
    c.font='800 34px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('二、重要时间安排',95,y);y+=60;rows(s).forEach(([label,date])=>{const active=label===event.eventType;c.fillStyle=active?red:ink;c.font=`${active?'800':'500'} 30px "PingFang SC","Microsoft YaHei",sans-serif`;c.fillText(`${label}：${fmt(date)}`,108,y);y+=50});y+=28;
    const registration=s.basic?.registrationUrl;c.fillStyle=ink;c.font='800 34px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('三、报名方式',95,y);y+=58;c.font='500 29px "PingFang SC","Microsoft YaHei",sans-serif';if(registration){y+=wrap(c,registration,108,y,860,43,3)}else{c.fillText('请通过考试官方渠道查看报名入口和具体要求。',108,y);y+=45}y+=35;
    c.font='800 34px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('四、考点信息',95,y);y+=57;c.font='500 29px "PingFang SC","Microsoft YaHei",sans-serif';y+=wrap(c,s.examCenter||'请以官方最新公布的考点信息为准。',108,y,860,43,3);y+=38;
    if(y<1960){c.font='800 34px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('五、温馨提示',95,y);y+=57;c.font='500 29px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('请及时关注官方通知，合理安排报名与备考时间。',108,y);y+=46;c.fillText('考试时间及考点如有调整，请以官方最新信息为准。',108,y)}
    return canvas}
  function safeName(v){return String(v||'考试快讯').replace(/[\\/:*?"<>|]/g,'-')}
  function fileName(event){if(event.monthCalendar)return`${event.year}年${event.month}月-小语种考试日历.png`;return`${safeName(event.examName)}-${safeName(event.sessionName||event.eventType)}-新通快讯.png`}
  function dataUrl(canvas){return canvas.toDataURL('image/png',1)}
  function blob(canvas){return new Promise((resolve,reject)=>{try{canvas.toBlob(b=>b?resolve(b):reject(new Error('图片转换失败')),'image/png',.96)}catch(e){reject(e)}})}
  const isMobile=()=>/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent);
  const isWechat=()=>/MicroMessenger/i.test(navigator.userAgent);
  async function imageFile(canvas,event){const b=await blob(canvas),name=fileName(event);return{blob:b,file:new File([b],name,{type:'image/png'}),name}}
  async function download(canvas,event){const pack=await imageFile(canvas,event);if(isMobile()&&navigator.share&&navigator.canShare?.({files:[pack.file]})){await navigator.share({files:[pack.file],title:`${event.examName}新通快讯`});return'share-save'}const url=URL.createObjectURL(pack.blob),a=document.createElement('a');a.href=url;a.download=pack.name;a.target='_blank';a.rel='noopener';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);return isMobile()?'opened':'downloaded'}
  async function share(canvas,event){const pack=await imageFile(canvas,event);if(navigator.share&&navigator.canShare?.({files:[pack.file]})){await navigator.share({files:[pack.file],title:`${event.examName}新通快讯`,text:`${event.examName}考试信息`});return'shared'}const url=URL.createObjectURL(pack.blob);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),120000);return isWechat()?'wechat-opened':'opened'}
  window.PosterEngine={create,download,share,dataUrl,fileName,blob,isMobile,isWechat};
})();
