(function(){
  const flags={日语:'🇯🇵',韩语:'🇰🇷',德语:'🇩🇪',法语:'🇫🇷',西班牙语:'🇪🇸',意大利语:'🇮🇹',俄语:'🇷🇺'};
  const nodeLabels={'报名注册开始':'即将开始报名注册','正式报名开始':'即将正式开始报名','正式报名截止':'报名即将截止','考试日期':'考试时间正式公布','出分日期':'成绩即将公布'};
  const scoreTemplates={topik:'assets/topik-score-template.jpg',testdaf:'assets/testdaf-score-template.jpg'};
  function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
  function fmt(v){const d=DateUtils.parseExcelDate(v);return d?`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日`:'待官方公布'}
  function wrap(c,text,x,y,w,lineHeight,max=99,align='left'){const chars=String(text||'').split(''),out=[];let line='';for(const ch of chars){if(ch==='\n'){out.push(line);line='';continue}if(c.measureText(line+ch).width>w&&line){out.push(line);line=ch}else line+=ch}if(line)out.push(line);c.textAlign=align;out.slice(0,max).forEach((v,i)=>c.fillText(v,x,y+i*lineHeight));c.textAlign='left';return Math.min(out.length,max)*lineHeight}
  function fitTitle(c,text,x,y,w,maxLines=3){let size=66;while(size>=44){c.font=`900 ${size}px "PingFang SC","Microsoft YaHei",sans-serif`;const chars=String(text).split('');let lines=1,line='';for(const ch of chars){if(c.measureText(line+ch).width>w&&line){lines++;line=ch}else line+=ch}if(lines<=maxLines)return wrap(c,text,x,y,w,size*1.18,maxLines,'center');size-=4}return wrap(c,text,x,y,w,54,maxLines,'center')}
  function rows(s){return[['报名注册开始',s.registrationStart],['正式报名开始',s.applicationStart],['正式报名截止',s.applicationDeadline],['考试日期',s.examDate],['出分日期',s.scoreDate]].filter(v=>v[1])}
  function scoreTemplateType(event){if(event.eventType!=='出分日期')return'';const id=String(event.examId||''),name=String(event.examName||'');if(id==='KR-TOPIK'||/TOPIK/i.test(name))return'topik';if(id==='DE-德福'||/TestDaF|德福/i.test(name))return'testdaf';return''}
  function drawDateBadge(c,date){const d=DateUtils.parseExcelDate(date)||new Date();c.fillStyle='#ef665f';c.fillRect(746,248,109,141);c.fillStyle='#fff';c.textAlign='center';c.font='500 52px Arial,sans-serif';c.fillText(String(d.getDate()).padStart(2,'0'),800.5,315);c.fillStyle='rgba(255,255,255,.72)';c.fillRect(759,327,83,2);c.font='700 27px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${String(d.getMonth()+1).padStart(2,'0')}月`,800.5,371);c.textAlign='left'}
  function plainDate(v){const d=DateUtils.parseExcelDate(v);return d?`${d.getFullYear()}.${d.getMonth()+1}.${d.getDate()}`:'待官方公布'}
  function topikEdition(s){const m=String(s.sessionName||'').match(/第\s*(\d+)\s*届/);return m?m[1]:String(s.year||new Date().getFullYear())}
  async function createScorePoster(event,type){const s=event.session||{},base=await loadImage(scoreTemplates[type]),canvas=document.createElement('canvas');canvas.width=base.naturalWidth;canvas.height=base.naturalHeight;const c=canvas.getContext('2d'),red='#c9002d',ink='#171717';c.drawImage(base,0,0);drawDateBadge(c,new Date());
    c.textAlign='center';c.fillStyle='#fff';c.fillRect(54,548,1017,type==='topik'?168:246);c.fillStyle=red;
    if(type==='testdaf'){c.font='800 55px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${s.year||event.year||new Date().getFullYear()}年中国大陆地区德福考试`,562,660);c.fillText('（TESTDAF）查分攻略',562,746);c.fillStyle='#fff';c.fillRect(105,3390,915,120);c.fillStyle=ink;c.font='700 31px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('祝福考生们都能取得理想的成绩，期待听到大家的好消息！！！！',562,3470)}
    else{c.font='800 61px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${topikEdition(s)}届TOPIK考试查分通知`,562,669);c.textAlign='left';c.fillStyle='#fff';c.fillRect(94,742,900,108);c.fillStyle=ink;c.font='500 35px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`考试时间： ${plainDate(s.examDate)}`,98,781);c.fillText(`成绩公布： ${plainDate(s.scoreDate||event.eventDate)} 15:00(北京时间)`,98,837)}
    c.textAlign='left';return canvas}
  async function create(event){const scoreType=scoreTemplateType(event);if(scoreType)return createScorePoster(event,scoreType);const s=event.session||{},base=await loadImage(window.POSTER_TEMPLATE_DATA||'assets/shinyway-info-template.jpg'),canvas=document.createElement('canvas');canvas.width=base.naturalWidth||1125;canvas.height=base.naturalHeight||2656;const c=canvas.getContext('2d'),red='#c9002d',ink='#141414';c.drawImage(base,0,0,canvas.width,canvas.height);
    // 原模板只替换日期牌内的数字。
    c.fillStyle='#ec635c';c.fillRect(774,267,112,144);const d=new Date();c.fillStyle='#fff';c.textAlign='center';c.font='500 52px sans-serif';c.fillText(String(d.getDate()).padStart(2,'0'),830,326);c.fillStyle='rgba(255,255,255,.65)';c.fillRect(790,346,80,2);c.fillStyle='#fff';c.font='700 27px sans-serif';c.fillText(`${String(d.getMonth()+1).padStart(2,'0')}月`,830,386);c.textAlign='left';
    // 覆盖原模板白色正文，仅动态填入本场考试数据。
    c.fillStyle='#fff';c.fillRect(60,523,1005,1660);let y=612;const sessionPrefix=s.sessionName||`${s.year||''}年${s.sessionMonth?`${s.sessionMonth}月`:''}场`,title=`${sessionPrefix}${event.examName}\n${nodeLabels[event.eventType]||event.eventType}`;c.fillStyle=red;y+=fitTitle(c,title,562,y,880,3)+20;c.fillStyle='#d1bfc2';c.fillRect(95,y,935,2);y+=75;
    c.fillStyle=ink;c.font='800 34px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('一、考试信息',95,y);y+=58;c.font='500 30px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText(`${flags[event.language]||'🌐'} 语种：${event.language||'其他'}`,108,y);y+=49;c.fillText(`考试名称：${event.examName}`,108,y);y+=49;y+=wrap(c,`考试场次：${s.sessionName||'以官方最新通知为准'}`,108,y,870,44,2);y+=36;
    c.font='800 34px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('二、重要时间安排',95,y);y+=60;rows(s).forEach(([label,date])=>{const active=label===event.eventType;c.fillStyle=active?red:ink;c.font=`${active?'800':'500'} 30px "PingFang SC","Microsoft YaHei",sans-serif`;c.fillText(`${label}：${fmt(date)}`,108,y);y+=50});y+=28;
    const registration=s.basic?.registrationUrl;c.fillStyle=ink;c.font='800 34px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('三、报名方式',95,y);y+=58;c.font='500 29px "PingFang SC","Microsoft YaHei",sans-serif';if(registration){y+=wrap(c,registration,108,y,860,43,3)}else{c.fillText('请通过考试官方渠道查看报名入口和具体要求。',108,y);y+=45}y+=35;
    c.font='800 34px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('四、考点信息',95,y);y+=57;c.font='500 29px "PingFang SC","Microsoft YaHei",sans-serif';y+=wrap(c,s.examCenter||'请以官方最新公布的考点信息为准。',108,y,860,43,3);y+=38;
    if(y<1960){c.font='800 34px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('五、温馨提示',95,y);y+=57;c.font='500 29px "PingFang SC","Microsoft YaHei",sans-serif';c.fillText('请及时关注官方通知，合理安排报名与备考时间。',108,y);y+=46;c.fillText('考试时间及考点如有调整，请以官方最新信息为准。',108,y)}
    return canvas}
  function safeName(v){return String(v||'考试快讯').replace(/[\\/:*?"<>|]/g,'-')}
  function fileName(event){return`${safeName(event.examName)}-${safeName(event.sessionName||event.eventType)}-新通快讯.png`}
  function dataUrl(canvas){return canvas.toDataURL('image/png',1)}
  function blob(canvas){return new Promise((resolve,reject)=>{try{canvas.toBlob(b=>b?resolve(b):reject(new Error('图片转换失败')),'image/png',.96)}catch(e){reject(e)}})}
  const isMobile=()=>/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent);
  const isWechat=()=>/MicroMessenger/i.test(navigator.userAgent);
  async function imageFile(canvas,event){const b=await blob(canvas),name=fileName(event);return{blob:b,file:new File([b],name,{type:'image/png'}),name}}
  async function download(canvas,event){const pack=await imageFile(canvas,event);if(isMobile()&&navigator.share&&navigator.canShare?.({files:[pack.file]})){await navigator.share({files:[pack.file],title:`${event.examName}新通快讯`});return'share-save'}const url=URL.createObjectURL(pack.blob),a=document.createElement('a');a.href=url;a.download=pack.name;a.target='_blank';a.rel='noopener';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);return isMobile()?'opened':'downloaded'}
  async function share(canvas,event){const pack=await imageFile(canvas,event);if(navigator.share&&navigator.canShare?.({files:[pack.file]})){await navigator.share({files:[pack.file],title:`${event.examName}新通快讯`,text:`${event.examName}考试信息`});return'shared'}const url=URL.createObjectURL(pack.blob);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),120000);return isWechat()?'wechat-opened':'opened'}
  window.PosterEngine={create,download,share,dataUrl,fileName,blob,isMobile,isWechat};
})();
