(function(){
  function varsFor(event,today=new Date()){
    const s=event.session||{},b=s.basic||{},score=DateUtils.formatDate(s.scoreDate,true);return{'今天日期':DateUtils.formatDate(today,true),'语种':event.language||s.language,'考试名称':event.examName||s.examName,'考试场次':event.sessionName||s.sessionName,'剩余天数':event.daysUntil,'节点日期':DateUtils.formatDate(event.eventDate,true),'更新类型':event.updateType||s.updateType,'更新说明':event.updateNote||s.updateNote||'该考试场次今日新增至考试日历。','考试日期':DateUtils.formatDate(s.examDate,true),'出分日期':score,'预计出分日期':score,'考试级别':b.levels,'考试频率':b.frequency,'通常考试月份':b.usualMonths}}
  function render(text,vars){return String(text||'').replace(/\{([^}]+)\}/g,(_,k)=>vars[k]!=null?String(vars[k]):'').replace(/\n{3,}/g,'\n\n').trim()}
  function updateText(e){const t=String(e.updateType||'');if(t==='首次录入')return'今日新增考试信息';if(t.includes('时间'))return'考试时间更新';return t?`信息更新：${t}`:'考试信息更新'}
  function dynamicLine(e){const icon=RadarEngine.emoji[e.language]||'🌐';if(e.eventType==='信息更新时间')return`${icon} ${e.examName}｜${e.sessionName}\n${updateText(e)}`;return`${icon} ${e.examName}｜${e.sessionName}\n${e.daysUntil===0?'今日'+e.eventType:`距离${e.eventType}${e.daysUntil>0?'还有':'已过去'}${Math.abs(e.daysUntil)}天`}`}
  function buildWechat(data,radar,today=new Date()){
    if(!radar.wechatEvents.length)return'';const tpl=data.wechat.find(t=>t.eventType==='每日汇总')||data.wechat[0];
    const vars={'今天日期':DateUtils.formatDate(today,true),'今日节点数量':radar.wechatEvents.length,'今日动态汇总':radar.wechatEvents.map(dynamicLine).join('\n\n'),'今日动作汇总':radar.advisorActions.map((a,i)=>`${['1️⃣','2️⃣','3️⃣','4️⃣','5️⃣'][i]||`${i+1}.`} ${a}`).join('\n')||'关注近期考试节点，及时同步目标学员。'};
    return tpl?`${render(tpl.title,vars)}\n\n${render(tpl.body,vars)}`:`📡【今日小语种考试营销雷达｜${vars.今天日期}】\n\n${vars.今日动态汇总}\n\n🎯 今日顾问建议动作：\n${vars.今日动作汇总}`;
  }
  function seedFor(event,today,type=''){const raw=`${DateUtils.dateKey(today)}|${event.eventId}|${type}`;let n=0;for(let i=0;i<raw.length;i++)n=(n*31+raw.charCodeAt(i))>>>0;return n}
  function pick(list,seed,offset=0){return list[(seed+offset)%list.length]}
  function shortDate(value){const s=String(value||''),m=s.match(/\d{4}-(\d{2})-(\d{2})/);return m?`${Number(m[1])}.${Number(m[2])}`:value}
  function sessionLabel(event){const s=event.session||{},month=s.sessionMonth||String(event.sessionName||'').match(/(\d{1,2})月/)?.[1];return`${month?month+'月':''}${event.examName}`}
  function dynamicTitle(type,event,vars,today){const exam=vars['考试名称'],label=sessionLabel(event),seed=seedFor(event,today,type),node=({'报名注册开始':'注册','正式报名开始':'报名','正式报名截止':'报名截止','考试日期':'考试','出分日期':'出分'}[event.eventType]||event.eventType);if(event.eventType==='出分日期')return pick([`🔥${exam}成绩节点来了，查分后别急着停`,`📣${exam}出分在即，下一步这样安排`,`✨${exam}出分提醒，努力即将揭晓`],seed);if(event.daysUntil<0&&event.eventType==='考试日期')return pick([`🔥${exam}考后复盘正当时`,`考完${exam}，下一阶段怎么走？`,`📚${exam}考后不停步，趁热开启新计划`],seed);if(type.includes('节点提醒'))return pick([`‼${label}${node}${event.daysUntil>0?'倒计时':''}`,`📣${label}${event.daysUntil===0?node+'今日正式启动':node+'即将启动'}`,`⏰${exam}${node}重要提醒`],seed);if(type.includes('专业规划'))return pick([`🎯${exam}时间线明确，备考规划现在开始`,`📚准备${exam}，这份时间安排请收好`,`🚀${exam}新节点，学习节奏这样安排`],seed);if(type.includes('轻营销'))return pick([`✨想学一门新语言，现在正是好时候`,`☀${exam}节点更新，新的目标可以安排了`,`🌍从${exam}出发，打开更多可能`],seed);if(type.includes('冲刺'))return`🚀${exam}进入关键冲刺阶段`;return`${exam}考试节点提醒`}
  function matchMoments(data,event){
    const all=Array.isArray(data.moments)?data.moments:[],exact=all.filter(t=>t.eventType===event.eventType&&t.marketingStage===event.marketingStage),sameNode=all.filter(t=>t.eventType===event.eventType),matched=exact.length?exact:sameNode;
    const types=['节点提醒型','专业规划型','轻营销型'],seen=new Set(),result=[];
    matched.forEach(t=>{const type=t.copyType||'节点提醒型';if(!seen.has(type)){seen.add(type);result.push(t)}});
    types.forEach((copyType,i)=>{if(!seen.has(copyType))result.push({templateId:`AUTO-${event.eventType}-${i}`,eventType:event.eventType,marketingStage:event.marketingStage,copyType,title:'',body:'',autoGenerated:true})});
    return result;
  }
  function timingText(event){if(event.daysUntil===0)return`今天迎来${event.eventType}节点`;if(event.daysUntil>0)return`距离${event.eventType}还有${event.daysUntil}天`;return`${event.eventType}已经过去${Math.abs(event.daysUntil)}天`}
  function dynamicMomentsBody(type,event,vars,today){
    const exam=vars['考试名称'],session=vars['考试场次'],level=vars['考试级别'],examDate=vars['考试日期'],scoreDate=vars['出分日期'],date=shortDate(event.eventDate),seed=seedFor(event,today,type),tomorrow=event.daysUntil===1,when=event.daysUntil===0?'今天':tomorrow?`明天（${date}）`:event.daysUntil>0?`${date}，还有${event.daysUntil}天`:`已过去${Math.abs(event.daysUntil)}天`,cta=pick(['想了解备考节奏和课程安排，欢迎随时滴滴～','需要考试规划的宝子，可以来聊聊你的目标～','还没理清时间线的同学，欢迎来找我一起规划～','想稳稳拿下目标等级，现在就可以开始准备啦～'],seed,7);
    if(event.eventType==='报名注册开始'||event.eventType==='正式报名开始')return pick([`📣${session||exam}报名，${event.daysUntil===0?'今日正式启动':'即将启动'}！\n⏰${when}${event.daysUntil>=0?'准时开放':''}\n⬇注册｜抢位｜缴费，全流程提前理清\n${RadarEngine.emoji[event.language]||'🌍'}准备报考的宝子们，速速码住🔥\n\n${cta}`,`‼${session||exam}报名${event.daysUntil>0?'倒计时':''}\n⏰${when}${event.daysUntil>=0?'记得定好闹钟':''}\n👇报名材料、考点与流程建议提前确认\n🉑准备冲刺的宝子随时滴滴～`, `📢${exam}${event.eventType}提醒\n${when}，重要节点别错过！\n✅账号注册 ✅资料检查 ✅考位准备\n先收藏，再按时间行动～\n\n${cta}`],seed);
    if(event.eventType==='正式报名截止')return pick([`‼${exam}报名进入最后倒计时\n⏰${when}截止，尚未完成的同学抓紧啦\n👇资料、考位和缴费状态再检查一遍\n错过就要等下一场！`,`📣${session||exam}报名即将截止\n倒计时${Math.max(0,event.daysUntil)}天，别把报名留到最后一刻\n✅确认信息 ✅完成缴费 ✅保存凭证\n转给身边正在备考的同学～`],seed);
    if(event.eventType==='考试日期'&&event.daysUntil>=0)return pick([`🚀${exam}考试${event.daysUntil===0?'就是今天':'进入倒计时'}\n📅${examDate||date}\n🎯最后阶段稳住节奏，查漏补缺比盲目刷题更重要\n愿大家从容上场，顺利拿下目标！`,`🔥${session||exam}即将开考\n⏰${when}\n✅证件与准考证 ✅路线与时间 ✅考试用品\n保持手感，轻装上阵，一次过！`],seed);
    if(event.eventType==='出分日期')return pick([`🔥${exam}出分提醒，查询入口记得收藏👇\n⏰${scoreDate||date}\n☀查分后别停，趁热复盘并安排下一阶段\n🉑想冲更高等级或学门新语言，随时滴滴！`,`📣${session||exam}成绩即将揭晓\n${when}\n无论结果如何，每一次备考都算数✨\n查分、复盘、下一等级规划，一次安排清楚～`],seed);
    if(event.eventType==='考试日期'&&event.daysUntil<0)return pick([`🔥${exam}考后复盘正当时\n📝答案与薄弱点趁记忆清晰及时整理\n☀考完别停，假期趁热打铁学门新语言\n🉑日韩法意德西俄，总有一门适合你！`,`🎯${exam}告一段落，新的目标可以开始了\n复盘不是纠结对错，而是让下一次准备更准确\n想冲更高等级或开启新语言，欢迎来聊聊～`],seed);
    if(type.includes('专业规划'))return`🎯${exam}时间线已经明确\n从目标等级倒推学习安排：\n① 评估当前基础${level?`与目标（${level}）`:''}\n② 拆分词汇、语法与专项能力\n③ 预留真题训练和冲刺时间\n\n规划越早，备考越从容。${cta}`;
    if(type.includes('轻营销'))return`✨最近关注${exam}的同学越来越多啦\n${session||exam} · ${timingText(event)}\n与其临近节点匆忙准备，不如早点找到适合自己的节奏。\n\n${cta}`;
    return`📌${exam}${session?`｜${session}`:''}\n${timingText(event)}\n请及时确认官方安排，并根据目标调整学习计划。\n\n${cta}`;
  }
  function buildMoments(data,event,today=new Date()){if(!event)return[];const vars=varsFor(event,today);return matchMoments(data,event).map(t=>{const type=t.copyType||'节点提醒型',dynamic=dynamicMomentsBody(type,event,vars,today),templateTitle=render(t.title,vars),templateBody=render(t.body,vars);return{...t,copyType:type,renderedTitle:dynamicTitle(type,event,vars,today)||templateTitle||`${vars['考试名称']}考试提醒`,renderedBody:dynamic||templateBody||`${vars['考试名称']}近期有新的考试节点，请及时关注官方安排。`}}).filter(t=>t.renderedTitle&&t.renderedBody)}
  window.TemplateEngine={render,varsFor,buildWechat,buildMoments,updateText};
})();
